apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: myaakoub/node-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: '8080'
        - name: REDIS_URL
          value: redis://redis.default.svc.cluster.local:6379
        - name: REDIS_REPLICAS_URL
          value: redis://redis.default.svc.cluster.local:6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deployment  
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

